services:
  postgres-db:
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  order-service:
    healthcheck:
      interval: 8s
      timeout: 5s
      retries: 15
      start_period: 30s

  payment-service:
    healthcheck:
      interval: 8s
      timeout: 5s
      retries: 15
      start_period: 30s

  shipping-service:
    healthcheck:
      interval: 8s
      timeout: 5s
      retries: 15
      start_period: 30s

  api-gateway:
    healthcheck:
      interval: 8s
      timeout: 5s
      retries: 15
      start_period: 20s

  frontend:
    healthcheck:
      interval: 8s
      timeout: 5s
      retries: 10
      start_period: 10s
