server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8084}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: notification-service
  data:
    mongodb:
      uri: ${NOTIFICATION_MONGODB_URI:mongodb+srv://USER:PASS@CLUSTER/food_delivery_notification_db?retryWrites=true&w=majority}
      auto-index-creation: true
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.1.100}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin123}
